# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f962f89eca97b282e193d7a1dec3632ccbee3044ba3b60a5af00af63bb1ba8fb2c3073f43000124aa72a152bd38a4b6c0b07d554cad4343bfe24afd3ee02fdf6

test:
  secret_key_base: 6f9f680b5d8180c93730985fd339b68fba8596111f9d22d13bc8a6487ec568093142b69893ee17bcb26573848ba94676b7548e10bb0ed5ad6978a88e2752763f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
